export const venues = [
  {
    id: '1',
    name: "Wayland's Yard",
    address: '6 Foregate St, Worcester WR1 1DB',
    phone: '01905 914100',
    image: 'https://images.squarespace-cdn.com/content/v1/5c7e7b1e7d0c912e5e18d0bb/1616429577682-4Q7J8E5N8K0L1P4Q9K9V/Waylands+Yard+Worcester+exterior.jpg',
    deal: '10% Off Food & Hot Drinks',
    online: 'https://www.waylandsyard.com/worcester',
    longDescription: "Wayland's Yard is a vibrant independent coffee shop and brunch spot in the heart of Worcester. Known for its specialty coffee and creative brunch menu, the venue welcomes dogs with open arms, offering dog treats and water bowls. Its spacious outdoor seating area is ideal for those sunny days, and the friendly staff ensure both you and your furry friend feel at home. With a relaxed, community-focused vibe, it’s the perfect spot for a catch-up or a work session accompanied by your pooch.",
    isFavourite: false,
  },
  {
    id: '2',
    name: 'Café Morso (Bromsgrove)',
    address: '14 High Street, Bromsgrove B61 8HQ',
    phone: '01527 758888',
    image: 'https://images.squarespace-cdn.com/content/v1/5b7c2782aadd34e7e8f2fa2a/1567582372637-9JYJ7ZQY6A3S6W2B1J3V/cafemorso-bromsgrove.jpg',
    deal: '10% Off Food & Hot Drinks',
    online: 'https://www.cafemorso.co.uk/bromsgrove',
    longDescription: "Café Morso in Bromsgrove is a welcoming local café serving artisan coffee, homemade cakes, and light lunches. Dogs are greeted with a smile and a complimentary biscuit, and water bowls are always available. The relaxed atmosphere and friendly staff make it a favourite among dog owners looking for a cozy spot to unwind after a walk through the town.",
    isFavourite: false,
  },
  {
    id: '3',
    name: 'Café Morso (Alvechurch)',
    address: '14A The Square, Alvechurch, Birmingham B48 7LA',
    phone: '0121 445 4411',
    image: 'https://images.squarespace-cdn.com/content/v1/5b7c2782aadd34e7e8f2fa2a/1567582372637-2EJYQ7QY7A3S6W2B1J3V/cafemorso-alvechurch.jpg',
    deal: '10% Off Food & Hot Drinks',
    online: 'https://www.cafemorso.co.uk/alvechurch',
    longDescription: "Nestled in the centre of Alvechurch, Café Morso is a popular spot for locals and their four-legged friends. With a menu full of fresh pastries and sandwiches, the café goes the extra mile for canine visitors, offering free puppuccinos and plenty of fuss. There’s ample space both inside and out, making it a year-round destination for dog lovers.",
    isFavourite: false,
  },
  {
    id: '4',
    name: 'Café Morso (Barnt Green)',
    address: '22 Hewell Rd, Barnt Green, Birmingham B45 8NE',
    phone: '0121 447 7757',
    image: 'https://images.squarespace-cdn.com/content/v1/5b7c2782aadd34e7e8f2fa2a/1567582372637-8JYJ7ZQY6A3S6W2B1J3V/cafemorso-barntgreen.jpg',
    deal: '10% Off Food & Hot Drinks',
    online: 'https://www.cafemorso.co.uk/barntgreen',
    longDescription: "Café Morso Barnt Green is renowned for its excellent coffee, friendly staff, and dog-friendly ethos. Dogs are welcome both inside and on the outdoor terrace, and can enjoy a breakfast sausage while their owners relax with a latte. The welcoming atmosphere and community feel make it a must-visit for dog owners in the area.",
    isFavourite: false,
  },
  {
    id: '5',
    name: 'Bayleys of Bromsgrove',
    address: '37 High Street, Bromsgrove B61 8AJ',
    phone: '01527 831338',
    image: 'https://images.squarespace-cdn.com/content/689876b74477501d91664398/1754822330685-6SDM1UHM9RH9H03WB7SE/bayleys.jpg?content-type=image%2Fjpeg',
    deal: '10% Off Food & Hot Drinks',
    online: 'https://www.bayleysbutchers.co.uk/',
    longDescription: "The Bayley brothers have combined their passion for great coffee, proper craft beer, and simple but delicious food, to create a coffee-shop-cum-tap-house that's rapdily captured the hearts of Bromsgrove residents.",
    isFavourite: false,
  },
];

export default venues;
